
export const iconsObject = ([
    "bi bi-fuel-pump",
    "bi bi-taxi-front",
    "bi bi-shop",
    "bi bi-airplane-engines",
    "bi bi-cart3",
    "bi bi-cup-hot",
    "bi bi-flower1",
    "bi bi-gift",
    "bi bi-piggy-bank",
    "bi bi-ticket-perforated",
    "bi bi-trash2-fill",
    "bi bi-universal-access",
    "bi bi-arrow-through-heart",
    "bi bi-tsunami",
    "bi bi-buildings",
    "bi bi-dribbble",
    "bi bi-credit-card-2-back",
    "bi bi-globe-europe-africa",
    "bi bi-music-note-beamed",
    "bi bi-eyedropper",
    "bi bi-clock",
    "bi bi-fire",
    "bi bi-scissors",
    "bi bi-inboxes",
    "bi bi-wrench-adjustable",
    "bi bi-incognito",
    "bi bi-mask",
    "bi bi-pin-angle",
    "bi bi-balloon",
    "bi bi-bicycle",
    "bi bi-cup-straw",
    "bi bi-cash-coin"
])

